server:
  port: 9090


eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8095/eureka
      defaultZone: ${EUREKA_URI:http://localhost:8095/eureka}
  instance:
    #hostname: localhost   #randon.value. = cualquier puesto no en uso
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


spring:
  application:
    name: ms-gateway-server


  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: ms-catalogo
              uri: lb://ms-catalogo
              predicates:
                - Path=/categoria/**
              filters:
                - AuthFilter

            - id: sm-marca
              uri: lb://sm-marca
              predicates:
                - Path=/marca/**
              

            - id: ms-auth
              uri: lb://ms-auth
              predicates:
                - Path=/auth/**                                                                                                                                                                                                                                                                                                                                                          ath=/auth/**

