server:
  port: 9090


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8095/eureka
  instance:
    hostname: localhost


spring:
  application:
    name: ms-gateway-server


  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: ms-catalogo
              uri: lb://ms-catalogo
              predicates:
                - Path=/categoria/**
