
server:
  #port: 8091
  port: ${PORT:${SERVER_PORT:0}}
spring:

  application:
    name: POSTGRES-PRUE-2

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_prueba
    username: postgres
    password: 1234567
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8095/eureka
      defaultZone: ${EUREKA_URI:http://localhost:8095/eureka}
  instance:
    #hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}