
server:
  port: 8091
spring:

  application:
    name: POSTGRES-PRUE-2

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_prueba
    username: postgres
    password: 1234567
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8095/eureka
  instance:
    hostname: localhost