
server:
  port: 8085
spring:
  
  application:
    name: sm_marca

  datasource:
    url: jdbc:mysql://localhost:3306/ms-marca
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html