server:
  port: 8088
spring:

  application:
    name: sm_marca2

  datasource:
    url: jdbc:mysql://localhost:3306/ms-marca
    username: root
    password: 1234567
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8095/eureka
  instance:
    hostname: localhost